import Head from "next/head";
import React from "react";

type Props = {
  children: React.ReactNode;
};
function Layout({ children }: Props) {
  return (
    <>
      <Head>
        <title>Scraper</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>{children}</div>
      </main>
    </>
  );
}

export default Layout;
