name: CICD
on: push
jobs:
  building:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Pull Data
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          command_timeout: 30m
          script: |
            cd scraper
            git pull origin master
      - name: Build
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          command_timeout: 30m
          script: |
            cd scraper
            git pull origin master
            docker build -t scraper .
  deploying:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          command_timeout: 30m
          script: |
            docker remove scraper
            docker stop scraper
            docker run --name scraper --rm -p 9000:3000 -d scraper
